name: Build and Push Docker Image

on:
  push:
    branches: [ main, master ]
  schedule:
    # Build every Monday at 6 AM UTC to get latest Firefox
    - cron: '0 6 * * 1'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Get Firefox version
      id: firefox_version
      run: |
        # Get current Firefox version from Alpine edge
        FIREFOX_VERSION=$(curl -s "https://pkgs.alpinelinux.org/package/edge/community/x86_64/firefox" | grep -oP '(?<=<td>)[0-9]+\.[0-9]+\.[0-9]+-r[0-9]+(?=</td>)' | head -1)
        echo "version=${FIREFOX_VERSION}" >> $GITHUB_OUTPUT
        echo "Firefox version: ${FIREFOX_VERSION}"
        
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        platforms: linux/amd64,linux/arm64
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/firefox:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/firefox:stable
          ${{ secrets.DOCKERHUB_USERNAME }}/firefox:${{ steps.firefox_version.outputs.version }}
        cache-from: type=gha
        cache-to: type=gha,mode=max